services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5001:5000"   # Exposed on host port 5001
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./registry-data:/var/lib/registry
    restart: unless-stopped


  proxy:
    image: nginx:alpine
    container_name: registry-proxy
    depends_on:
      - registry
    ports:
      - "443:443"       # Expose portless FQDN via standard HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/registry.g1.crt:/etc/ssl/certs/registry.g1.crt:ro
      - ./certs/registry.g1.key:/etc/ssl/private/registry.g1.key:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped




  # Docker-in-Docker builder
  # mainly to be able to access $REGISTRY_FQDN via self-signed-certificate via docker
  builder:
    build:
      context: ./container/builder
    container_name: builder
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=""
    volumes:
      - ../:/work   # Workspace for builds
      - ./dind-data:/var/lib/docker
      - ./daemon.json:/etc/docker/daemon.json:ro  # Mount insecure registry config
      # Self-signed registry CA
      - ./certs/registry.g1/myCA.crt:/etc/docker/certs.d/registry.g1/ca.crt:ro
      # Registry public certificate (optional)
      - ./certs/registry.g1.crt:/etc/docker/certs.d/registry.g1/registry.g1.crt:ro
    working_dir: /work
    stdin_open: true
    tty: true
    restart: unless-stopped
    extra_hosts:
      - "registry.g1:host-gateway"

  # mainly to be able to access $REGISTRY_FQDN via self-signed-certificate via https.
  xpkg-builder:
    build:
      context: ./container/xpkg-builder
    container_name: xpkg
    privileged: true               # required for dind
    volumes:
      - ../:/work
    entrypoint: ["sleep", "infinity"]   # keep container running
    extra_hosts:
      - "registry.g1:host-gateway"
