events { worker_connections 1024; }

http {
    server {
        listen 443 ssl;
        server_name registry.g1;

         client_max_body_size 0;
        ssl_certificate     /etc/ssl/certs/registry.g1.crt;
        ssl_certificate_key /etc/ssl/private/registry.g1.key;

        location / {
            proxy_pass http://registry:5000;
        }
    }
}


#events {}
#http {
#    server {
#        listen 80;
#        server_name registry.g1;
#
#        client_max_body_size 2000M;  # <-- allow up to 2 GB
#
#        location / {
#            proxy_pass http://host.docker.internal:5001/;
#            proxy_set_header  Host $host;
#            proxy_set_header  X-Real-IP $remote_addr;
#            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
#            proxy_set_header  X-Forwarded-Proto $scheme;
#        }
#    }
#}

